// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {minimax} from '../models';
import {config} from '../models';
import {main} from '../models';

export function CaptureNow():Promise<void>;

export function Correct(arg1:string):Promise<string>;

export function Describe(arg1:string):Promise<minimax.Suggestion>;

export function Dismiss(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetPending():Promise<Array<main.PendingView>>;

export function HidePopup():Promise<void>;

export function NowParts():Promise<Record<string, string>>;

export function OpenWorklogFile():Promise<void>;

export function PendingCount():Promise<number>;

export function Recapture(arg1:string):Promise<string>;

export function RevealWorklogFolder():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetFilePath(arg1:string):Promise<void>;

export function SetPaused(arg1:boolean):Promise<void>;

export function ShowManual():Promise<void>;

export function ShowSettings():Promise<void>;

export function Submit(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SubmitManual(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ToggleConfidential():Promise<boolean>;
