// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureNow() {
  return window['go']['main']['App']['CaptureNow']();
}

export function Correct(arg1) {
  return window['go']['main']['App']['Correct'](arg1);
}

export function Describe(arg1) {
  return window['go']['main']['App']['Describe'](arg1);
}

export function Dismiss(arg1) {
  return window['go']['main']['App']['Dismiss'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPending() {
  return window['go']['main']['App']['GetPending']();
}

export function HidePopup() {
  return window['go']['main']['App']['HidePopup']();
}

export function NowParts() {
  return window['go']['main']['App']['NowParts']();
}

export function OpenWorklogFile() {
  return window['go']['main']['App']['OpenWorklogFile']();
}

export function PendingCount() {
  return window['go']['main']['App']['PendingCount']();
}

export function Recapture(arg1) {
  return window['go']['main']['App']['Recapture'](arg1);
}

export function RevealWorklogFolder() {
  return window['go']['main']['App']['RevealWorklogFolder']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetFilePath(arg1) {
  return window['go']['main']['App']['SetFilePath'](arg1);
}

export function SetPaused(arg1) {
  return window['go']['main']['App']['SetPaused'](arg1);
}

export function ShowManual() {
  return window['go']['main']['App']['ShowManual']();
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}

export function Submit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Submit'](arg1, arg2, arg3, arg4);
}

export function SubmitManual(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SubmitManual'](arg1, arg2, arg3, arg4, arg5);
}
